package com.rejowan.onboardingjc.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF5836B5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF7D5EDD)
val onPrimaryContainerLight = Color(0xFFFFFFFF)
val secondaryLight = Color(0xFF635788)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFDBCEFF)
val onSecondaryContainerLight = Color(0xFF433867)
val tertiaryLight = Color(0xFF8D2175)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBA499C)
val onTertiaryContainerLight = Color(0xFFFFFFFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF7FF)
val onBackgroundLight = Color(0xFF1D1A22)
val surfaceLight = Color(0xFFFDF7FF)
val onSurfaceLight = Color(0xFF1D1A22)
val surfaceVariantLight = Color(0xFFE7DFF2)
val onSurfaceVariantLight = Color(0xFF494553)
val outlineLight = Color(0xFF7A7584)
val outlineVariantLight = Color(0xFFCAC4D5)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF322F37)
val inverseOnSurfaceLight = Color(0xFFF5EEFA)
val inversePrimaryLight = Color(0xFFCDBDFF)

val primaryDark = Color(0xFFCDBDFF)
val onPrimaryDark = Color(0xFF370095)
val primaryContainerDark = Color(0xFF795AD9)
val onPrimaryContainerDark = Color(0xFFFFFFFF)
val secondaryDark = Color(0xFFCDBFF7)
val onSecondaryDark = Color(0xFF342957)
val secondaryContainerDark = Color(0xFF433867)
val onSecondaryContainerDark = Color(0xFFDBCEFF)
val tertiaryDark = Color(0xFFFFADE2)
val onTertiaryDark = Color(0xFF5F004E)
val tertiaryContainerDark = Color(0xFFB54598)
val onTertiaryContainerDark = Color(0xFFFFFFFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF14121A)
val onBackgroundDark = Color(0xFFE6E0EB)
val surfaceDark = Color(0xFF14121A)
val onSurfaceDark = Color(0xFFE6E0EB)
val surfaceVariantDark = Color(0xFF494553)
val onSurfaceVariantDark = Color(0xFFCAC4D5)
val outlineDark = Color(0xFF948E9F)
val outlineVariantDark = Color(0xFF494553)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE6E0EB)
val inverseOnSurfaceDark = Color(0xFF322F37)
val inversePrimaryDark = Color(0xFF6646C5)







